[package]
name = "day_23"
version = "0.1.0"
authors = ["Oliver Breitwieser <oliver.breitwieser@kip.uni-heidelberg.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
nom = "6"
